name: Bug Report
description: Report a bug or unexpected behaviour
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug. Please fill out the sections below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Minimal steps to reproduce the behaviour.
      placeholder: |
        1. Run `make ...`
        2. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Relevant versions and system info. Run `make info` if available.
      placeholder: |
        - OS: macOS 14 / Ubuntu 24.04 / Windows 11
        - Python: 3.13.x
        - rhiza version:
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Logs, screenshots, or anything else that may be helpful.
    validations:
      required: false
